# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Deploy-CICD

on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build Project
        run: mvn clean install -DskipTests
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build docker image
        run: docker build -t tiagofrancarita/backend-loja-virtual-shirt .
      - name: Publish image to docker hub
        run: docker push tiagofrancarita/backend-loja-virtual-shirt:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull tiagofrancarita/backend-loja-virtual-shirt:latest
      - name: Delete old container
        run: docker rm -f backend-loja-virtual-shirt-container
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name backend-loja-virtual-shirt-container tiagofrancarita/backend-loja-virtual-shirt