name: Deploy-CICD-DEV
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11"
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build Project
        run: mvn clean install -DskipTests
      - uses: actions/checkout@v3
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build docker image
        run: docker build -t tiagofrancadev/shirtvirtual .
      - name: Publish image to docker hub
        run: docker push tiagofrancadev/shirtvirtual:latest